name: Daily arXiv Report

on:
  schedule:
    # 毎日UTC 00:00 (JST 09:00)に実行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # レポートをコミット・プッシュするための権限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run arXiv reporter
      env:
        GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
        GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: |
        python process_papers_and_email.py
